import {useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {FiBarChart2,FiBox,FiChevronDown,FiDollarSign,FiEdit2,FiFileText,FiGrid,FiLogOut,FiMenu,FiPlus,FiSearch,FiSettings,FiShoppingBag,FiTrash2,FiUsers,FiX} from 'react-icons/fi'
import {money} from '../components/UI'
import {orders,products} from '../data'
import toast from 'react-hot-toast'
import {api} from '../lib/api'
export function AdminLogin(){const nav=useNavigate();const [loading,setLoading]=useState(false);const submit=async e=>{e.preventDefault();setLoading(true);const form=new FormData(e.currentTarget);try{const result=await api('/auth/login',{method:'POST',body:JSON.stringify({email:form.get('email'),password:form.get('password')})});localStorage.setItem('godavari-admin',result.token);toast.success('Welcome back');nav('/admin')}catch(error){if(import.meta.env.DEV&&form.get('email')==='admin@godavari.in'&&form.get('password')==='admin123'){localStorage.setItem('godavari-admin','development-preview');toast.success('Development preview');nav('/admin')}else toast.error(error.message)}finally{setLoading(false)}};return <div className="login-page"><div className="login-art"><div><span>GODAVARI</span><h1>Commerce,<br/><em>considered.</em></h1><p>Manage your collection, customers, and content from one calm workspace.</p></div></div><div className="login-form"><Link to="/" className="back">← Back to storefront</Link><form onSubmit={submit}><span className="eyebrow">Admin portal</span><h2>Welcome back</h2><p>Enter your credentials to continue.</p><label>Email address<input name="email" type="email" defaultValue="admin@godavari.in" autoComplete="username" required/></label><label>Password<input name="password" type="password" defaultValue="admin123" autoComplete="current-password" required minLength="6"/></label><button className="btn dark" disabled={loading}>{loading?'Signing in…':'Sign in securely'}</button><small>Development preview: admin@godavari.in / admin123</small></form></div></div>}
const navItems=[[FiGrid,'Overview'],[FiBox,'Products'],[FiShoppingBag,'Orders'],[FiUsers,'Customers'],[FiFileText,'Content'],[FiSettings,'Settings']]
export function AdminDashboard(){const [section,setSection]=useState('Overview');const [side,setSide]=useState(false);const [query,setQuery]=useState('');const nav=useNavigate();const logout=()=>{localStorage.removeItem('godavari-admin');nav('/admin/login')};return <div className="admin"><aside className={side?'open':''}><div className="admin-logo">GE <span>Godavari</span><button onClick={()=>setSide(false)}><FiX/></button></div><nav>{navItems.map(([I,n])=><button key={n} className={section===n?'active':''} onClick={()=>{setSection(n);setSide(false)}}><I/>{n}</button>)}</nav><button className="logout" onClick={logout}><FiLogOut/> Sign out</button></aside><main><header><button className="admin-menu" onClick={()=>setSide(true)}><FiMenu/></button><div><span className="eyebrow">Admin workspace</span><h1>{section}</h1></div><div className="admin-user"><span>AK</span><div><strong>Abhishek Kumar</strong><small>Administrator</small></div><FiChevronDown/></div></header>{section==='Overview'?<Overview/>:section==='Products'?<Products query={query} setQuery={setQuery}/>:section==='Orders'?<Orders/>:section==='Customers'?<Customers/>:<Content title={section}/>}</main></div>}
function Overview(){return <div className="admin-body"><div className="stat-grid">{[[FiBox,'Total products','128','+12 this month'],[FiShoppingBag,'Total orders','1,048','+8.2%'],[FiUsers,'Customers','3,842','+124 this month'],[FiDollarSign,'Revenue','₹12.8L','+18.4%']].map(([I,l,v,c])=><div className="stat" key={l}><I/><span>{l}</span><strong>{v}</strong><small>{c}</small></div>)}</div><div className="admin-panels"><section className="chart"><div className="panel-title"><div><h3>Revenue overview</h3><p>Monthly sales performance</p></div><select><option>Last 6 months</option></select></div><div className="bars">{[48,61,54,76,68,92].map((h,i)=><div key={i}><span style={{height:`${h}%`}}/><small>{['Jan','Feb','Mar','Apr','May','Jun'][i]}</small></div>)}</div></section><section><div className="panel-title"><div><h3>Recent orders</h3><p>Latest customer purchases</p></div></div><OrderTable compact/></section></div></div>}
function Products({query,setQuery}){const list=products.filter(p=>p.title.toLowerCase().includes(query.toLowerCase()));return <div className="admin-body"><div className="table-toolbar"><label><FiSearch/><input placeholder="Search products" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="btn dark" onClick={()=>toast('Product editor ready for API connection')}><FiPlus/> Add product</button></div><div className="data-table"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th/></tr></thead><tbody>{list.map(p=><tr key={p.id}><td><div className="product-cell"><img src={p.images[0]}/><strong>{p.title}</strong></div></td><td>{p.category}</td><td>{money(p.price)}</td><td>{p.stock}</td><td><span className="status delivered">Active</span></td><td><button aria-label="Edit"><FiEdit2/></button><button aria-label="Delete" onClick={()=>toast.error('Demo mode: deletion disabled')}><FiTrash2/></button></td></tr>)}</tbody></table></div></div>}
function OrderTable(){return <div className="data-table"><table><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Total</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>{o.id}</strong></td><td>{o.customer}</td><td>{o.date}</td><td>{money(o.total)}</td><td><span className={`status ${o.status.toLowerCase()}`}>{o.status}</span></td></tr>)}</tbody></table></div>}
function Orders(){return <div className="admin-body"><div className="table-toolbar"><label><FiSearch/><input placeholder="Search orders"/></label><select><option>All statuses</option><option>Pending</option><option>Shipped</option><option>Delivered</option><option>Cancelled</option></select></div><OrderTable/></div>}
function Customers(){return <div className="admin-body"><div className="stat-grid"><div className="stat"><FiUsers/><span>Active customers</span><strong>3,842</strong><small>+18.4% year on year</small></div><div className="stat"><FiBarChart2/><span>Repeat purchase rate</span><strong>34.2%</strong><small>Healthy retention</small></div></div><div className="empty admin-empty"><FiUsers/><h3>Customer directory</h3><p>Search, segment, and manage customer enquiries here.</p></div></div>}
function Content({title}){return <div className="admin-body"><div className="content-editor"><FiFileText/><h2>{title} management</h2><p>Update homepage banners, story copy, social links, contact details, and theme settings without changing code.</p><button className="btn dark" onClick={()=>toast.success('Draft saved')}>Save draft</button></div></div>}
