import {useState} from 'react'
import toast from 'react-hot-toast'
import {FiMail,FiMapPin,FiMessageCircle,FiPhone} from 'react-icons/fi'
import {PageHero} from '../components/UI'
import {api} from '../lib/api'

export default function Contact(){
 const [loading,setLoading]=useState(false)
 const submit=async event=>{event.preventDefault();setLoading(true);const form=event.currentTarget;const data=new FormData(form);try{await api('/inquiries',{method:'POST',body:JSON.stringify({name:`${data.get('firstName')} ${data.get('lastName')}`.trim(),email:data.get('email'),phone:data.get('phone'),message:`${data.get('interest')}: ${data.get('message')}`})});form.reset();toast.success('Thank you — our team will be in touch shortly.')}catch(error){toast.error(error.message)}finally{setLoading(false)}}
 return <><PageHero eyebrow="Contact" title="We’d love to hear from you." copy="Whether you’re choosing one piece or building a retail assortment, there’s a real person here to help."/><section className="contact-grid wrap"><div className="contact-form"><h2>Start a conversation</h2><form onSubmit={submit}><div className="form-row"><label>First name<input name="firstName" autoComplete="given-name" required/></label><label>Last name<input name="lastName" autoComplete="family-name" required/></label></div><label>Email address<input name="email" type="email" autoComplete="email" required/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel"/></label><label>I’m interested in<select name="interest"><option>Shopping assistance</option><option>Wholesale partnership</option><option>Order support</option><option>Custom production</option></select></label><label>How can we help?<textarea name="message" rows="5" required/></label><button className="btn dark" disabled={loading}>{loading?'Sending…':'Send enquiry'}</button></form></div><aside className="contact-info"><div><FiMapPin/><h3>Visit our office</h3><p>Textile Market, Ring Road<br/>Surat, Gujarat 395002</p></div><div><FiPhone/><h3>Call us</h3><p>+91 99999 99999<br/><small>Mon–Sat, 10am–7pm</small></p></div><div><FiMail/><h3>Write to us</h3><p>care@godavarienterprises.in<br/>wholesale@godavarienterprises.in</p></div><a href="https://wa.me/919999999999" className="whatsapp"><FiMessageCircle/> Chat on WhatsApp</a></aside></section><section className="map"><iframe title="Godavari Enterprises location" loading="lazy" src="https://www.google.com/maps?q=Textile%20Market%20Surat&output=embed"/></section></>
}
