import {publicAsset} from './lib/assets'

export const products=[
 {id:'ivory-chanderi-set',title:'Ivory Chanderi Set',category:'Women',type:'Festive',price:4890,oldPrice:5490,rating:4.9,badge:'New',images:[publicAsset('images/products/ivory-chanderi-set.jpg')],sizes:['XS','S','M','L','XL'],colors:['#eee8dc','#762f2f'],stock:14,description:'A luminous Chanderi kurta set finished with restrained zari detailing and an easy, contemporary silhouette.'},
 {id:'midnight-bandhgala',title:'Midnight Bandhgala',category:'Men',type:'Occasion',price:6990,rating:4.8,badge:'Bestseller',images:[publicAsset('images/products/midnight-bandhgala.jpg')],sizes:['S','M','L','XL','XXL'],colors:['#222222','#433c35'],stock:8,description:'Precision tailored in a rich charcoal weave, designed for celebrations that call for quiet distinction.'},
 {id:'handloom-sand-saree',title:'Handloom Sand Saree',category:'Women',type:'Sarees',price:3590,rating:4.7,badge:'Limited',images:[publicAsset('images/products/handloom-sand-saree.jpg')],sizes:['Free'],colors:['#b89b79','#7e2525'],stock:6,description:'Airy handloom drape with a subtle woven border, made to move effortlessly from day to evening.'},
 {id:'stone-linen-shirt',title:'Stone Linen Shirt',category:'Men',type:'Essentials',price:2290,rating:4.6,badge:'New',images:[publicAsset('images/products/stone-linen-shirt.jpg')],sizes:['S','M','L','XL'],colors:['#d6d0c4','#ffffff'],stock:22,description:'A breathable linen-blend shirt with a softened handfeel and a clean, relaxed cut.'},
 {id:'wine-silk-kurta',title:'Wine Silk Kurta',category:'Men',type:'Festive',price:3290,rating:4.8,badge:'Trending',images:[publicAsset('images/products/wine-silk-kurta.jpg')],sizes:['S','M','L','XL'],colors:['#5c1d29','#18312e'],stock:10,description:'A refined silk kurta in a deep wine tone, with tonal embroidery and considered finishing.'},
 {id:'black-drape-dress',title:'Black Drape Dress',category:'Women',type:'Contemporary',price:3990,rating:4.7,badge:'Editor’s pick',images:[publicAsset('images/products/black-drape-dress.jpg')],sizes:['XS','S','M','L'],colors:['#171717'],stock:9,description:'Fluid draping and a sculpted neckline give this evening silhouette its understated impact.'},
 {id:'everyday-cotton-kurta',title:'Everyday Cotton Kurta',category:'Men',type:'Essentials',price:1890,rating:4.5,badge:'',images:[publicAsset('images/products/everyday-cotton-kurta.jpg')],sizes:['S','M','L','XL','XXL'],colors:['#d8cbb0','#8d9b90'],stock:28,description:'Lightweight cotton, clean lines, and an unfussy fit for repeat everyday wear.'},
 {id:'rose-organza-saree',title:'Rose Organza Saree',category:'Women',type:'Sarees',price:4290,rating:4.9,badge:'New',images:[publicAsset('images/products/rose-organza-saree.jpg')],sizes:['Free'],colors:['#d5a3a6','#e7d9c5'],stock:7,description:'Weightless organza in dusty rose with a delicate scalloped edge and tonal embroidery.'}
]
export const orders=[{id:'GE-1048',customer:'Aarav Mehta',date:'18 Jun 2026',total:9280,status:'Shipped'},{id:'GE-1047',customer:'Diya Shah',date:'18 Jun 2026',total:4890,status:'Packed'},{id:'GE-1046',customer:'Neha Kapoor',date:'17 Jun 2026',total:7580,status:'Confirmed'},{id:'GE-1045',customer:'Rohan Iyer',date:'16 Jun 2026',total:2290,status:'Delivered'}]
